### PR TITLE
Feature/todo

### PR DESCRIPTION
**Pull request by jdmartinez1062**
Completed the required requirements for the to do project

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @jdmartinez1062 and @wrakc, great job on this project :+1: PR :100: README is professional:+1:  However, there are a couple of issues we need to address before proceeding :slightly_smiling_face: Kindly check the comments below:
- We should be able to edit our todo
- We should be able to delete our todo
- Adding a todo do not show in any of the available projects including the one I created

[Optional]
- Currently, we are able to submit empty data which is not good. Let us add validations to our form
- Also the UI can be improved so that using the app will be much easier and fun. 

Once these are fixed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by carlosveigadev** [comment]
Thanks, @addod19 for the review, we improved the code as suggested:
* It is now possible to edit the ToDo when the person clicks twice on the ToDo fields.
* It is now possible to delete a ToDo;
* An arrow that indicates you can expand the ToDo to check its content.
 * The user cannot leave empty spaces when filling the form now.

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team. 💻 👀 ✨ 

## However, there are some changes required 👀 🧰 🔨 🔧 
- As the previous TSE mentioned, the user interface is a bit complicated and difficult to use. Here are some suggestions to improve it:
- Instead of giving the user a single chance to add ToDos to a project, change the application so that the user can add and delete ToDos to a project even *after* the project has been created. Implement an "Add ToDo" button on the project view, to allow the user to do this.
- It's not immediately obvious that the user must double-click the ToDo description to edit it. Also: I'm not able to edit the checklist, or the date of the ToDo. Being able to edit a ToDo means being able to edit everything in it, not just one thing.
- To do this, you may use the ToDo creation form you already wrote. Just add an 'Edit' button to the ToDo in the project view, which, when clicked, opens up a form just like the one for creating the ToDo, but instead of being empty, already contains all the data from the ToDo you want to edit. This is far more intuitive and will let the user edit everything with ease.
- Also add a similar edition function for the project.
### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by carlosveigadev** [comment]
Hi @voscarmv, thanks for the review. We improved the project as suggested.
- Implement the "Add ToDo" button on the project view;
- Implement the "Edit" for the project;

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 

Great job @team, and thanks for making the required changes.

now you can merge your project is approved :checkered_flag: 

## Happy Coding :tophat:

**Pull request merged**
